### ISSUE TITLE
Tilem doesn't launch / white screen.

### ISSUE THREAD

**Issue by corndog2000** [timower/rM2-stuff#11]
I installed Tilem with toltec but launching Tilem from a launcher shows a blank white screen.

I am using the remarkable 2 version 2.10.3.379

**Comment by corndog2000** [comment]
Ok, I used `wget `to download the room to` /home/root`. I had to restart my remarkable 2 and then the app launched correctlyo.

**Comment by timower** [comment]
Hmm, tilem should show a dialog to download the rom. So this might actually be an issue.

**Comment by qubist** [comment]
I got the dialogue and followed the prompts to install the ROM, but when I launch Tillem, I get the calculator UI with a blank calculator screen, even after restart. Happy to troubleshoot if it'll help!
