### ISSUE TITLE
How to open Tilem inside notebook like in the README

### ISSUE THREAD

**Issue by corndog2000** [timower/rM2-stuff#13]
How do you open the calculator app inside of a notebook like you show in the readme?

**Comment by timower** [comment]
Hi, when merging into toltec it was decided it'd be less confusing to take up the whole screen.
You should be able to disable the clearing of the background by removing the `Cleared` widget in:
https://github.com/timower/rM2-stuff/blob/8dc94a360358bf74da244beda74739663dd44741/apps/tilem/main.cpp#L520

Then it's up to your launching method to not clear the framebuffer before starting tilem.
