### ISSUE TITLE
[yaft] nano won't start, and vi starts very weird.

### ISSUE THREAD

**Issue by cesss** [timower/rM2-stuff#15]
I just installed yaft from the current toltec. I tried to run nano and it won't start, complaining cannot open yaft-256color. If I try to run 'vi', it first complains about some "cm" capability missing, and then I get the welcome screen quite weird... when trying to type commands, I get like Ctrl (^) characters... really weird.

OTOH, if I go to the screenshot you have in your docs folder, I see you have 'vi' running very nicely, even with two terminal views, one showing 'top' or similar, and you even have function keys in the keyboard (which I don't, see my screenshot). Can you tell me the steps and keys you pressed for getting that screenshot? (I mean this: https://github.com/timower/rM2-stuff/blob/master/doc/yaft.png)

These are my screenshots showing the issues I mention:
![IMG_1163](https://user-images.githubusercontent.com/15330020/202249163-ab66b41a-06cb-4cd8-bca3-15327a20debe.jpg)
![IMG_1164](https://user-images.githubusercontent.com/15330020/202249161-29e197de-2290-48d4-8aac-68cb50fb1d64.jpg)
![IMG_1162](https://user-images.githubusercontent.com/15330020/202249157-bc605838-15f1-4c2a-adf5-22438778de4b.jpg)

**Comment by cesss** [comment]
Found the reason for 'nano' not starting and 'vi' acting so weird: You need to set $TERM as xterm instead of yaft-256color. Anyway, my question remains regarding the steps needed to get the function keys in the keyboard, and how to get to your screenshot.

**Comment by timower** [comment]
yaft-256color is the correct term. You just need to make sure the terminfo files have been installed correctly, then vim and other should recognize it.

**Comment by timower** [comment]
This is fixed by sourcing `/opt/etc/profile` as described in https://github.com/toltec-dev/toltec/pull/715
