### ISSUE TITLE
Handle SYN_DROPPED

### ISSUE THREAD

**Issue by Eeems** [timower/rM2-stuff#16]
Your current handling of input events doesn't currently handle dropping an event if [SYN_DROPPED](SYN_DROPPED) is encountered. This could be useful to make the event flood slightly less noisy if every application supported it properly.

**Comment by timower** [comment]
I'm using libevdev which should handle SYN_DROPPED for me: https://www.freedesktop.org/software/libevdev/doc/1.1/syn_dropped.html

Unless there's a bug in my code: [here](https://github.com/timower/rM2-stuff/blob/6b7f07f5473a5aa08d5f649301e29f8375d511f0/libs/rMlib/Input.cpp#L65C3-L89C22)

**Comment by Eeems** [comment]
If libevdev automatically handles it, then I have no concerns.
