### ISSUE TITLE
Unfinished TODO can cause Bus error

### ISSUE THREAD

**Issue by Eeems** [timower/rM2-stuff#17]
https://github.com/timower/rM2-stuff/blob/9126d7ff3093e5598342a7236f305e6331d9ed79/libs/rMlib/FrameBuffer.cpp#L199

If the framebuffer has a different resolution or virtual resolution than normal for any reason, you will get a `Bus error` crash when launching yaft or tilem. I assume rocket has the same flaw.

**Comment by Eeems** [comment]
@timower have you had a chance to look at this?

**Comment by timower** [comment]
Will your implementation support `FBIOPUT_VSCREENINFO` to request a window size?

**Comment by timower** [comment]
Actually, this should be fixed in 88e14de484b939eacf7ceb70dbb

**Comment by Eeems** [comment]
> Will your implementation support `FBIOPUT_VSCREENINFO` to request a window size?

Not currently, but there is a TODO comment to add it eventually. Right now you'd need to use the window API to ask for it.

> Actually, this should be fixed in [88e14de](https://github.com/timower/rM2-stuff/commit/88e14de484b939eacf7ceb70dbb449bfd212c834)

Thanks, I'll have to test when I get back to this,
