### ISSUE TITLE
missing dependency: xochitl

### ISSUE THREAD

**Issue by aomua** [timower/rM2-stuff#27]
It is really awesome that rm2fb has support for 3.3.x and even 3.5.x, but for some reason when I try to install th rm2fb.ipk the opkg (I used [Evidlo's Entware](https://github.com/Evidlo/remarkable_entware)) outputs:

`
 * pkg_hash_check_unresolved: cannot find dependency xochitl for rm2fb
 * satisfy_dependency_for: Cannot satisify the following dependencies for rm2fb
:
 * xochitl
 * opkg_install_cmd: Cannot install package rm2fb.
`

I can enable xochitl by `systemctl enable xochitl`.
I can run xochitl by `xochitl`.

I have tried to `opkg install /rm2fb` on 2.15, 3.3, 3.5, and 3.8 using fake updates with no avail. I am not sure what to do.

**Comment by timower** [comment]
rm2fb depends on the xochitl package from https://github.com/toltec-dev/toltec/tree/stable/package/xochitl
If you're not using toltec that dependency won't be found.

**Comment by aomua** [comment]
> rm2fb depends on the xochitl package from https://github.com/toltec-dev/toltec/tree/stable/package/xochitl If you're not using toltec that dependency won't be found.

I see! I suppose this package can be installed without toltec? I am just really trying to wrap my mind around how you got things working with version 3.3.x and above.

**Comment by timower** [comment]
You can install toltec just fine on 3.3.2, and then install the packages from the repo on top.
No need to use [Evidlo's Entware](https://github.com/Evidlo/remarkable_entware)

**Comment by aomua** [comment]
> You can install toltec just fine on 3.3.2, and then install the packages from the repo on top. No need to use [Evidlo's Entware](https://github.com/Evidlo/remarkable_entware)

Ah, that makes much more sense now. Thanks!
