### ISSUE TITLE
install koreader on remarkable 2 version 3.9

### ISSUE THREAD

**Issue by sife33** [timower/rM2-stuff#33]
hi everyone 
first I'M new here and I'm sorry for my English
my request is that I wanna install koreader in my remarkable 2 which have Version 3.9 
I dont konw if this is possible ; i think I can't do it without tolec after version 2.15 
note : I'm not a programmer I just know  basics things about computer that's why I hope there are some steps which I need just use ssh commend to  
install it 
thanks in advance

**Comment by timower** [comment]
Hey,
We do not yet support 3.9 in this repo.
I think the easiest way to achieve koreader on your device is to have a second partition downgrade to 2.15 and use toltec.
For help please check out toltec: https://toltec-dev.org/#frequently-asked-questions
