### ISSUE TITLE
rm2fb issues when switching apps in remux or oxide

### ISSUE THREAD

**Issue by Eeems** [timower/rM2-stuff#44]
As part of investigating integrating your version of rm2fb into toltec for 3.5.2 and 3.8.2 support, I've discovered what I would consider a blocking bug.

When the launchers switch between running applications they will often fail to fully render the saved screen for the application. This behaviour does not happen with the upstream rm2fb on older OS versions.

You can find some screenshots of the issue in the following comments:
- https://github.com/toltec-dev/toltec/pull/860#issuecomment-2130451543
- https://github.com/toltec-dev/toltec/pull/860#issuecomment-2130750412
- https://github.com/toltec-dev/toltec/pull/860#issuecomment-2130753085

**Comment by timower** [comment]
I can reproduce issues with part of the screen being blank in the calculator app. 
I think they changed how they interpret the colors in the framebuffer (which bits being which color), but I'll have to confirm.
Does the attached video match what you're seeing?

https://drive.google.com/file/d/1lmqqbrVg5fe8iFm2We3LW5mk8TkusyDg/view?usp=sharing

**Comment by Eeems** [comment]
That does look like what I'm seeing, just with a different mechanism to trigger it.

**Comment by timower** [comment]
Turns out I was hooking the QImage constructor when I shouldn't. So easy fix

**Comment by StarNumber12046** [comment]
Sill also seems to not display anything

**Comment by Eeems** [comment]
> actually, I'll upload a screenshot (with bufshot over rm2fb client) and a picture of the rM with sill supposedly running
> ![fb](https://github.com/timower/rM2-stuff/assets/64470722/5bc706d0-866f-4b21-870b-1264df8ad1d0)
> ![PXL_20240529_132646733](https://github.com/timower/rM2-stuff/assets/64470722/eaae9191-e71c-44d8-97b8-84480a910aa2)
>  

I'm assuming you built your own copy of rm2fb with the changes timowers created and this is what you are seeing? Did you include any of the changes made in the toltec PR to fix up the environment at all?

**Comment by StarNumber12046** [comment]
I'll test it later today

Il mer 29 mag 2024, 18:20 StarNumber Official <
***@***.***> ha scritto:

**Comment by Eeems** [comment]
The latest release does not contain the changed code yet.

**Comment by timower** [comment]
I'll make a release with the fix, then it'll be easier to verify

**Comment by StarNumber12046** [comment]
> When the launchers switch between running applications they will often fail to fully render the saved screen for the application. This behaviour does not happen with the upstream rm2fb on older OS versions.

This seems to be the same root cause as yaft having its keyboard disappear

**Comment by StarNumber12046** [comment]
(it is now fixed)

**Comment by timower** [comment]
How are you getting sill to run?
For me it fails with:
```
thread 'main' panicked at 'Failed to open swtfb shared buffer: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /root/.cargo/git/checkouts/libremarkable-e1fa5419bec94e16/5b9316a/src/framebuffer/core.rs:128:18
```
Because it tries to re-implement the rm2fb client protocol

**Comment by StarNumber12046** [comment]
![image](https://github.com/timower/rM2-stuff/assets/64470722/861ba72b-6e75-4f0c-9221-c07f0a93f607)
![image](https://github.com/timower/rM2-stuff/assets/64470722/5c4ad74a-b789-4e8d-bfee-2d08eb6f1288)

**Comment by StarNumber12046** [comment]
https://github.com/toltec-dev/toltec/pull/860#issuecomment-2130531958

**Comment by raisjn** [comment]
> Because it tries to re-implement the rm2fb client protocol

@timower: swtfb.01 is used by rm2fb in /dev/shm , i believe you changed it to rm2fb.01 (not sure if you changed it back yet) in your implementation. likely gonna break libremarkable apps (sill) and also bufshot (thanks @Eeems  for finding this)
