### ISSUE TITLE
yaft screen rotation?

### ISSUE THREAD

**Issue by addcninblue** [timower/rM2-stuff#8]
Hello!

Thanks so much for the port of yaft to RM. I was wondering how much work it would be to also support screen rotation? I see that this is a feature in this branch [1], but I'm unsure if that's ported to the RM.

No worries, if it's a lot of work; I'm just curious. Pointers to how I can implement this myself would be appreciated!

Thanks!

[1]: https://github.com/uobikiemukot/yaft/issues/17#issuecomment-372968519

**Comment by BloodChiefStromberg** [comment]
Also interested with this! I'm trying to do it myself, but I'm new to c++, can't even get YAFT to build yet. Happy to help however I can though.

**Comment by timower** [comment]
Yeah, this is on my TODO list (that I've been neglecting for a few months).
Problem with rotation is that you can't memcpy whole lines anymore as drawing screen rows now doesn't match the row-first framebuffer. So you'd have to copy/draw character by character probably.

**Comment by wehlutyk** [comment]
I'd be happy to try and help here, is any first stop that can be done?
